// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {services} from '../models';
import {models} from '../models';

export function AnalyzeFile(arg1:string):Promise<main.FileInfo>;

export function ConvertFile(arg1:string,arg2:string):Promise<main.ConversionResult>;

export function CreateChecklist(arg1:services.CreateChecklistRequest):Promise<services.ChecklistCreationResult>;

export function CreateChecklistFromStigs(arg1:services.CreateChecklistRequest):Promise<services.ChecklistWithItems>;

export function DeleteImportedStigs(arg1:Array<number>):Promise<void>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetImportedStigs():Promise<Array<models.ImportedSTIGSummary>>;

export function ImportStigBundle(arg1:string):Promise<void>;

export function ImportStigBundleDialog():Promise<string>;

export function LoadChecklistFromFile(arg1:string):Promise<services.ChecklistWithItems>;

export function OpenFileDialog():Promise<string>;

export function SaveChecklistToFile(arg1:services.ChecklistWithItems,arg2:string,arg3:string):Promise<void>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function ValidateFile(arg1:string):Promise<main.FileInfo>;
