// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeFile(arg1) {
  return window['go']['main']['App']['AnalyzeFile'](arg1);
}

export function ConvertFile(arg1, arg2) {
  return window['go']['main']['App']['ConvertFile'](arg1, arg2);
}

export function CreateChecklist(arg1) {
  return window['go']['main']['App']['CreateChecklist'](arg1);
}

export function CreateChecklistFromStigs(arg1) {
  return window['go']['main']['App']['CreateChecklistFromStigs'](arg1);
}

export function DeleteImportedStigs(arg1) {
  return window['go']['main']['App']['DeleteImportedStigs'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetImportedStigs() {
  return window['go']['main']['App']['GetImportedStigs']();
}

export function ImportStigBundle(arg1) {
  return window['go']['main']['App']['ImportStigBundle'](arg1);
}

export function ImportStigBundleDialog() {
  return window['go']['main']['App']['ImportStigBundleDialog']();
}

export function LoadChecklistFromFile(arg1) {
  return window['go']['main']['App']['LoadChecklistFromFile'](arg1);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function SaveChecklistToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveChecklistToFile'](arg1, arg2, arg3);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function ValidateFile(arg1) {
  return window['go']['main']['App']['ValidateFile'](arg1);
}
